before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/flowflow
    ldflags:
      - -s -w
      - -X github.com/avanibbles/flowflow/internal.Version={{.Version}}
      - -X github.com/avanibbles/flowflow/internal.CommitHash={{.FullCommit}}
      - -X github.com/avanibbles/flowflow/internal.BuildTimestamp={{.Timestamp}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
