definitions:
  apimodels.HttpError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  v1.VersionResponse:
    properties:
      build_timestamp:
        type: string
      commit_hash:
        type: string
      version:
        type: string
    type: object
info:
  contact: {}
  title: flowflow api
  version: vNext
paths:
  /api/v1/hack/err/{code}:
    get:
      description: Make an error
      parameters:
      - description: http code
        in: path
        name: code
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apimodels.HttpError'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apimodels.HttpError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apimodels.HttpError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/apimodels.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apimodels.HttpError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/apimodels.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apimodels.HttpError'
      summary: Make an error
      tags:
      - hack
  /api/v1/version:
    get:
      description: Get flowflow version
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.VersionResponse'
      summary: Get flowflow version
      tags:
      - version
swagger: "2.0"
