version: '2'

services:
  minio:
    image: docker.io/bitnami/minio:2022
    expose:
      - "9000"
      - "9001"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9001:9001"
    hostname: minio
    networks:
      - app
    volumes:
      - minio-data:/minio

  postgres:
    container_name: postgres_container
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - app
    restart: unless-stopped

volumes:
  minio-data:
    driver: local
  postgres:
    driver: local
  pgadmin:
    driver: local

networks:
  app:
    driver: bridge
