// Code generated by go-swagger; DO NOT EDIT.

package version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/avanibbles/flowflow/pkg/models"
)

// GetAPIV1VersionReader is a Reader for the GetAPIV1Version structure.
type GetAPIV1VersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1VersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1VersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIV1VersionOK creates a GetAPIV1VersionOK with default headers values
func NewGetAPIV1VersionOK() *GetAPIV1VersionOK {
	return &GetAPIV1VersionOK{}
}

/* GetAPIV1VersionOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1VersionOK struct {
	Payload *models.V1VersionResponse
}

func (o *GetAPIV1VersionOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionOK  %+v", 200, o.Payload)
}
func (o *GetAPIV1VersionOK) GetPayload() *models.V1VersionResponse {
	return o.Payload
}

func (o *GetAPIV1VersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1VersionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
