name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  # issues: write
jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get all tags
        run: git fetch --force --tags
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  container-release:
    runs-on: ubuntu-latest
    steps:
      - name: get current date
        run: echo "BUILD_TIME=$(date -u --iso-8601=seconds)" >> $GITHUB_ENV
      - name: sanitize repo name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username:  ${{ github.repository_owner }}
          password:  ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:${{ github.ref_name }}
            ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.REPO_NAME }}:latest
          build-args: VERSION=${{github.ref_name}},COMMIT_HASH=${{github.sha}},BUILD_TIMESTAMP=$BUILD_TIME